# Generated by Django 4.1.2 on 2022-11-07 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geometry', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Logs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=120)),
                ('method', models.CharField(choices=[('G', 'GET'), ('P', 'Post')], max_length=10)),
                ('time', models.DateTimeField()),
            ],
        ),
    ]
