# Generated by Django 4.1.2 on 2022-11-07 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geometry', '0002_logs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logs',
            name='method',
            field=models.CharField(choices=[('P', 'Post'), ('G', 'Get')], max_length=10),
        ),
    ]
